services:
  
  mlflow:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks: [mlflow]
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --default-artifact-root "${S3_ARTIFACT_ROOT}"
      --backend-store-uri postgresql://mlflow:mlflow_pass@postgres:5432/mlflow_db

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow_pass
      POSTGRES_DB: mlflow_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [mlflow]

volumes:
  pgdata:

networks:
  mlflow: {}
